# contenido de tests/__init__.py
'''from .test_tablero import TestTablero
from .test_jugador import TestJugador
from .test_juego import TestJuego
from .test_dado import TestDado
from .test_turno import TestTurno
from .test_estado import TestEstado
from .test_fichas import TestFichas
from .test_moneda import TestMoneda
from .test_ficha import TestFicha'''